name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'aks-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      env:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

    - name: Build and push Docker image
      env:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      run: |
        IMAGE_NAME=${ACR_LOGIN_SERVER}/aksapp
        docker build -t $IMAGE_NAME -f aks-app/webapi/Dockerfile aks-app/webapi
        docker push $IMAGE_NAME

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Set up Helm
      run: helm repo add stable https://charts.helm.sh/stable

    - name: Deploy to AKS using Helm
      run: helm upgrade --install mymicroserviceapp ./aks-app/charts/mymicroserviceapp --set mymicroserviceapp.image.tag=latest
